services:

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: okf
      POSTGRES_USER: okf
      POSTGRES_PASSWORD: okf
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U okf -d okf"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  rabbitmq:
    image: rabbitmq:4-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: okf
      RABBITMQ_DEFAULT_PASS: okf
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  minio:
    image: minio/minio
    restart: unless-stopped
    command: server /data --console-address ":9001"

    environment:
      MINIO_ROOT_USER: okfadmin
      MINIO_ROOT_PASSWORD: okfpassword

    ports:
      - "9000:9000" #9001web, 9000 minIO
      - "9001:9001"

    volumes:
      - minio_data:/data

  api:
    build:
      context: ./backend
      args:
        SERVICE: api

    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
      DATABASE_URL: postgres://okf:okf@postgres:5432/okf?sslmode=disable

    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      minio:
        condition: service_started

  worker:
    build:
      context: ./backend
      args:
        SERVICE: worker

    restart: unless-stopped

    environment:
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/

    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      minio:
        condition: service_started

  frontend:
    build:
      context: ./frontend

    ports:
      - "5173:80"

    depends_on:
      - api


volumes:
  postgres_data:
  rabbitmq_data:
  minio_data: